---
name: Bug report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug']
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Run command '...'
2. With credentials '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Error output**
If applicable, add the error message or stack trace.

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Ubuntu]
 - Python version: [e.g. 3.12.0]
 - Lock & Key version: [e.g. 1.0.1]
 - Cloud provider: [e.g. AWS, Azure, GCP]

**Additional context**
Add any other context about the problem here.
